import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import { ConvexClerkProvider } from "@/providers/convex-clerk-providers";
import { NEXTUIProviders } from "./providers";
import { cn } from "@nextui-org/react";
// import "../app/globals.css";

const fontSans = FontSans({
   subsets: ["latin"], 
   variable: "--font-sans",
  });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ConvexClerkProvider>
      <html lang="en">
        <body className={cn(
          "min-h-screen bg-background",
          fontSans.variable
        )}>
          <NEXTUIProviders>
            {children}
          </NEXTUIProviders>
        </body>
      </html>
    </ConvexClerkProvider>
  );
}
